/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_it6604_hdmirx_HdmirxActivity */

#ifndef _Included_com_it6604_hdmirx_HdmirxActivity
#define _Included_com_it6604_hdmirx_HdmirxActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_it6604_hdmirx_HdmirxActivity
 * Method:    hdmirx_native_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL switvideo_1native_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_it6604_hdmirx_HdmirxActivity
 * Method:    hdmirx_native_grun
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_switvideo_1native_1grun
  (JNIEnv *, jclass);

/*
 * Class:     com_it6604_hdmirx_HdmirxActivity
 * Method:    hdmirx_native_exit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_switvideo_1native_1exit
  (JNIEnv *, jclass);

/*
 * Class:     org_monitor_display_CaptureImage
 * Method:    video_native_fieldset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_switvideo_1native_1fieldset
  (JNIEnv *, jclass);

/*
 * Class:     org_monitor_display_CaptureImage
 * Method:    video_native_getsize
 * Signature: ()Lorg/monitor/display/videoSize;
 */
JNIEXPORT jobject JNICALL Java_switvideo_1native_1getsize
  (JNIEnv *, jclass);

/*
 * Class:     org_monitor_display_CaptureImage
 * Method:    switvideo_native_setinterface
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_switvideo_1native_1setinterface
  (JNIEnv *, jclass, jint);

int jniThrowException(JNIEnv* env, const char* className, const char* msg);

JNIEnv* getJNIEnv();

int jniRegisterNativeMethods(JNIEnv* env,
                             const char* className,
                             const JNINativeMethod* gMethods,
                             int numMethods);
#ifdef __cplusplus
}
#endif
#endif
