/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jpf_myjni_MyJNI */

#ifndef _Included_com_jpf_myjni_MyJNI
#define _Included_com_jpf_myjni_MyJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jpf_myjni_MyJNI
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jpf_myjni_MyJNI_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
